const musics=[
    {
        id:0,
        name: "Cheerleader",
        author: "OMI",
        path: "./music/Cheerleader-OMI.mp3",
        thumbnail: "./images/Cheerleader-OMI.png",
        duration: "2:54",
    },
    {
        id:1,
        name: "Faded",
        author: "Alan Walker",
        path: "./music/Faded-AlanWalker.mp3",
        thumbnail: "./images/Faded.png",
        duration: "3:32",
    },
    {
        id:2,
        name: "The Nights",
        author: "AVICII",
        path: "./music/The Nights-Avicii.mp3",
        thumbnail: "./images/theNightAvicii.png",
        duration: "3:10",
    },
    {
        id:3,
        name: "Anywhere",
        author: "Ikson",
        path: "./music/Anywhere - Ikson.mp3",
        thumbnail: "./images/Anywhere-Ikson.png",
        duration: "2:59",
    },
    {
        id:4,
        name: "Adventures",
        author: "A Himitsu",
        path: "./music/Adventures - A Himitsu.mp3",
        thumbnail: "./images/Adventures-A Himitsu.png",
        duration: "3:44",
    },
]